version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mymongo
    ports:
      - "27000:27017"
    volumes:
      - mongodata:/data/db
    command: --bind_ip 0.0.0.0

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongodb
volumes:
  mongodata:

